apiVersion: cluster.redpanda.com/v1alpha1
kind: Redpanda
metadata:
  name: redpanda
  namespace: redpanda
spec:
  chartRef: {}
  clusterSpec:
    # External Service Access Settings
    external:
      # makes the domain of redpana nodes to be advertised with
      # .localhost as domain name e.g. redpanda-0.localhost
      domain: localhost
      externalDns:
        enabled: true
    # since its dev local cluster can disable TLS
    tls:
      enabled: false
    statefulset:
      replicas: 1
    # Redpanda Console settings
    console:
      service:
        type: NodePort
        port: 8080
        nodePort: 30080
      # https://docs.redpanda.com/docs/reference/console/config/
      console:
        config:
          kafka:
            brokers: ["redpanda:9093"]
            schemaRegistry:
              enabled: true
              urls: ["http://redpanda:8081"]
            protobuf:
              enabled: true
              schemaRegistry:
                enabled: true
                refreshInterval: 5m
          redpanda:
            adminApi:
              enabled: true
              urls: ["http://redpanda:9644"]
